### ISSUE TITLE
Encounter Callback error

### ISSUE THREAD

**Issue by maickel** [galedric/FS_Core#10]
Hi,
I'm currently getting an error on my module : [FA.T18.ArchimondeMod.lua
](https://github.com/maickel/FS_Core_Modules/blob/master/FA.T18.ArchimondeMod.lua) 
It seems to be related to ElvUI, and may be with this commit 62d2fef5b8fd6a4c329f4408350221337e32d2c9 . But I guess my code is the problem ... 

``` lua
1x FS_Core\Encounters.lua:302: attempt to call method 'ClearIntercepts' (a nil value)
FS_Core\Encounters.lua:302: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:145: in function <...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:145>
[string "safecall Dispatcher[6]"]:4: in function <[string "safecall Dispatcher[6]"]:4>
[C]: ?
[string "safecall Dispatcher[6]"]:13: in function `?'
...que\Libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...faceElvUI\libs\AceEvent-3.0\AceEvent-3.0-3.lua:120: in function <...faceElvUI\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals:
nil
```

Thanks !
PS: I'm using your latest code.

**Comment by BastienClement** [comment]
> PS: I'm using your latest code.

Are you sure? Which version / revision exactly?

`Encounters.lua:302` is:

``` lua
BigWigs:ClearIntercepts()
```

The reported error does not complain about `BigWigs` being nil but rather `ClearIntercepts`.

However, `BigWigs.lua:146`:

``` lua
function BW:ClearIntercepts()
    wipe(intercepts)
end
```

And I don't recall any error related to during in yesterday testing. This repository is up to date with my latest changes and I've just downloaded the Curse package (0.8-beta12) to check and it is too.

Can you check both of your files or the package version you have from Curse?
Thanks

**Comment by maickel** [comment]
Apparently it was all my fault, I had a old version ! Now it's working. 
Thanks
