### ISSUE TITLE
Overrun direction on PolyLineObject 

### ISSUE THREAD

**Issue by maickel** [galedric/FS_Core#5]
It would be nice to implement a `direction` argument on the `:Overrun` function.
For the moment I'm using a custom class (base on `PolyLineObject`) in WA called `RayLineObject` for the _Wrought Chaos_ on Archimonde MM.

**Comment by BastienClement** [comment]
It shouldn't be too hard to split the `overrun` field into `overrun_from` and `overrun_to` and change the `:Overrun` method to take two arguments, defaulting to setting both values if only one argument is provided.

I'm currently using `:DrawLine` to draw Wrought Chaos on Archimonde. Thus, I don't have `:Overrun` and had to implement a custom `point:Position` method on a shadow point referencing the target player. Something like this:

``` lua
local pt = Hud:CreateShadowPoint(target)
function pt:Position()
    local x, y = self.ref:Position()
    -- Some code to "move" x,y 100yd away from the ray source while preserving direction
    -- IIRC, the Geometry module provide methods to do this easily.
    return x, y
end

Hud:DrawLine(source, pt)
```

It's another way to do it without extending built-in objects, which is generally a better idea.

**Comment by maickel** [comment]
I didn't think about this `:CreateShadowPoint` solution :+1: 
Thanks for the tips !
