### ISSUE TITLE
Slash commands don't work on clean environment

### ISSUE THREAD

**Issue by maickel** [galedric/FS_Core#6]
Hi,
Yesterday I was trying to share a module I did with a friend trough `Pacman` (really nice !), he installed `FS_Core` but he was not able to call either `/fs` or `/pacman`, the only main difference between us was `Elvui`.

So I tried to remove all the plugins except `FS_Core` and I manage to reproduce this, nothing pop up on slash command. 

There is no lua error, just telling the command doesn't exist.

**Comment by BastienClement** [comment]
I'm doing most of my tests with a rather clean environment, except for libraries.

And it seems one of these libraries is not properly loaded.

```
Message: ...ce\AddOns\FS_Core\Ace3\AceEvent-3.0\AceEvent-3.0.lua:21: Cannot find a library instance of "CallbackHandler-1.0".
Time: 03/30/16 16:03:31
Count: 1
Stack: [C]: in function `error'
Interface\AddOns\FS_Core\LibStub\LibStub.lua:38: in function `GetLibrary'
...ce\AddOns\FS_Core\Ace3\AceEvent-3.0\AceEvent-3.0.lua:21: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "CallbackHandler-1.0"."
```

I'm working on it!

**Comment by BastienClement** [comment]
It looks like 0.7-beta3 fixes it.

http://wow.curseforge.com/addons/fs_core/files/168-0-7-beta3/

Thx a lot for the ticket.
