### ISSUE TITLE
:DrawText function in Hud

### ISSUE THREAD

**Issue by maickel** [galedric/FS_Core#7]
It would be nice if you can implement a `:DrawText` function in `Hud`, most of the time I want to be able to see some information near points, like name of a character, number of stacks, number of people in the area etc ...

I did this horrible snippet, and at the moment I have to copy it over all my modules. I can may be create a `Librairy`, don't know exactly how it's working in `Pacman`.

I think this feature should be include in `Hud`.

``` lua
function DrawText(center, text, args)
  local obj = Hud:CreateObject()

  local default = {
    font= "Friz Quadrata TT", 
    size= 14, 
    outline= "OUTLINE",
    color={0.5,0.5,0.5,1.0},
    offset={0,15},
  }

  for k,v in pairs(default) do
    if args[k] == nil then 
      args[k] = v
    end
  end

  center = obj:UsePoint(center)
  if not center then return end
  obj.frame:SetWidth (100)
  obj.frame:SetHeight(100)
  if not obj.frame.text then
    obj.frame.text = obj.frame:CreateFontString(nil, "OVERLAY")
  end

  obj.frame.text:SetFont(args.font, args.size, args.outline)
  obj.frame.text:SetText(text)
  obj.frame.text:SetTextColor(unpack(args.color))
  obj.frame.text:SetPoint("CENTER", unpack(args.offset))
  obj.frame.text:Show()

  function obj:Update()
    if self.OnUpdate then self:OnUpdate() end
    self.frame:SetPoint("CENTER", center.x, center.y)
  end

  function obj:SetText(...)
    self.frame.text:SetText(...)
    return self
  end

  function obj:Remove()
    self.frame.text:SetText("")
    self.frame.text:Hide()
    HudObject.Remove(self)
  end
  return obj
end
```

Thanks,
Maickel

**Comment by BastienClement** [comment]
Thanks for this code. This was on my radar for quite some time.
I'll take a look at it and certainly merge it into FS Core.

In the future, you are also free to open a Pull Request if you have working code to submit :)

**Comment by maickel** [comment]
I'm not used to Git, so many things to learn ! ; ) 
I tried to make a `Pull Request`, 55d5cd234b90ca5776e5e91dbc57a362f02836ed. Not sure about the code either, you may want to clean it : )
